title: Charbel-Raphaël Segerie # your name (or website title) here
logo: "/images/circle_me.PNG?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hi, I am a researcher in Artificial Intelligence.
  <br><br>
  I also have a penchant for neuroscience, philosophy and music.
  <br><br>
  <a href="https://www.linkedin.com/in/charbel-raphael-segerie/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
